2025-02-11 17:21:04,545 - INFO - Starting Chrome WebDriver...
2025-02-11 17:21:04,545 - INFO - ====== WebDriver manager ======
2025-02-11 17:21:11,112 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-11 17:21:11,312 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-11 17:21:11,421 - INFO - There is no [mac64] chromedriver "132.0.6834.159" for browser google-chrome "132.0.6834" in cache
2025-02-11 17:21:11,449 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-11 17:21:12,091 - INFO - WebDriver version 132.0.6834.159 selected
2025-02-11 17:21:12,095 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/mac-arm64/chromedriver-mac-arm64.zip
2025-02-11 17:21:12,095 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/mac-arm64/chromedriver-mac-arm64.zip
2025-02-11 17:21:12,387 - INFO - Driver downloading response is 200
2025-02-11 17:21:14,663 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-11 17:21:14,835 - INFO - Driver has been saved in cache [/Users/claudio/.wdm/drivers/chromedriver/mac64/132.0.6834.159]
2025-02-11 17:21:17,661 - INFO - Accessing URL: https://cinepolischile.cl/cartelera/santiago-oriente/cinepolis-mallplaza-egana
2025-02-11 17:21:47,778 - WARNING - Attempt 1 failed. Retrying...
2025-02-11 17:21:47,779 - ERROR - An error occurred: cannot access local variable 'time' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/claudio/dev/imax-santiago/check-movies-json.py", line 54, in list_cinepolis_imax_movies
    driver.get(url)
    ~~~~~~~~~~^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.017
  (Session info: chrome=132.0.6834.162)
Stacktrace:
0   chromedriver                        0x00000001005db0d4 cxxbridge1$str$ptr + 2600792
1   chromedriver                        0x00000001005d39f0 cxxbridge1$str$ptr + 2570356
2   chromedriver                        0x00000001001743d8 cxxbridge1$string$len + 89376
3   chromedriver                        0x000000010015f6c0 cxxbridge1$string$len + 4104
4   chromedriver                        0x000000010015f460 cxxbridge1$string$len + 3496
5   chromedriver                        0x000000010015d168 chromedriver + 184680
6   chromedriver                        0x000000010015ddd4 chromedriver + 187860
7   chromedriver                        0x000000010016ba70 cxxbridge1$string$len + 54200
8   chromedriver                        0x000000010017f8d0 cxxbridge1$string$len + 135704
9   chromedriver                        0x000000010015e400 chromedriver + 189440
10  chromedriver                        0x000000010017f798 cxxbridge1$string$len + 135392
11  chromedriver                        0x00000001001f357c cxxbridge1$string$len + 609988
12  chromedriver                        0x00000001001ad34c cxxbridge1$string$len + 322708
13  chromedriver                        0x00000001001adf94 cxxbridge1$string$len + 325852
14  chromedriver                        0x00000001005a6238 cxxbridge1$str$ptr + 2384060
15  chromedriver                        0x00000001005a9550 cxxbridge1$str$ptr + 2397140
16  chromedriver                        0x000000010058cb9c cxxbridge1$str$ptr + 2279968
17  chromedriver                        0x00000001005a9e10 cxxbridge1$str$ptr + 2399380
18  chromedriver                        0x000000010057e6a4 cxxbridge1$str$ptr + 2221352
19  chromedriver                        0x00000001005c47d8 cxxbridge1$str$ptr + 2508380
20  chromedriver                        0x00000001005c4954 cxxbridge1$str$ptr + 2508760
21  chromedriver                        0x00000001005d3664 cxxbridge1$str$ptr + 2569448
22  libsystem_pthread.dylib             0x00000001988cf2e4 _pthread_start + 136
23  libsystem_pthread.dylib             0x00000001988ca0fc thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/claudio/dev/imax-santiago/check-movies-json.py", line 62, in list_cinepolis_imax_movies
    time.sleep(5)
    ^^^^
UnboundLocalError: cannot access local variable 'time' where it is not associated with a value
2025-02-11 17:21:47,875 - INFO - WebDriver closed successfully
2025-02-11 17:21:47,876 - INFO - Successfully saved movies.json
2025-02-11 17:22:44,254 - INFO - Starting Chrome WebDriver...
2025-02-11 17:22:44,255 - INFO - ====== WebDriver manager ======
2025-02-11 17:22:44,884 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-11 17:22:44,994 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-11 17:22:45,140 - INFO - Driver [/Users/claudio/.wdm/drivers/chromedriver/mac64/132.0.6834.159/chromedriver-mac-arm64/chromedriver] found in cache
2025-02-11 17:22:46,545 - INFO - Accessing URL: https://cinepolischile.cl/cartelera/santiago-oriente/cinepolis-mallplaza-egana
2025-02-11 17:23:16,669 - WARNING - Attempt 1 failed. Retrying...
2025-02-11 17:23:51,760 - WARNING - Attempt 2 failed. Retrying...
2025-02-11 17:24:09,009 - INFO - Waiting for movie elements to load...
2025-02-11 17:24:09,041 - INFO - Found 77 movie articles
2025-02-11 17:24:09,269 - INFO - Processing IMAX movie: NOSFERATU
2025-02-11 17:24:09,285 - INFO - Found 1 showtimes for NOSFERATU
2025-02-11 17:24:09,312 - INFO - Processing IMAX movie: INTERSTELLAR: 10 ANIVERSARIO
2025-02-11 17:24:09,326 - INFO - Found 1 showtimes for INTERSTELLAR: 10 ANIVERSARIO
2025-02-11 17:24:09,461 - INFO - WebDriver closed successfully
2025-02-11 17:24:09,462 - INFO - Successfully saved movies.json
2025-02-15 15:19:38,999 - INFO - Starting Chrome WebDriver...
2025-02-15 15:19:39,000 - INFO - ====== WebDriver manager ======
2025-02-15 15:19:44,543 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-15 15:19:44,691 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-15 15:19:44,789 - INFO - There is no [mac64] chromedriver "133.0.6943.98" for browser google-chrome "133.0.6943" in cache
2025-02-15 15:19:44,796 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-15 15:19:45,301 - INFO - WebDriver version 133.0.6943.98 selected
2025-02-15 15:19:45,304 - INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.98/mac-arm64/chromedriver-mac-arm64.zip
2025-02-15 15:19:45,304 - INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.98/mac-arm64/chromedriver-mac-arm64.zip
2025-02-15 15:19:45,650 - INFO - Driver downloading response is 200
2025-02-15 15:19:47,489 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-15 15:19:47,648 - INFO - Driver has been saved in cache [/Users/claudio/.wdm/drivers/chromedriver/mac64/133.0.6943.98]
2025-02-15 15:19:49,557 - INFO - Accessing URL: https://cinepolischile.cl/cartelera/santiago-oriente/cinepolis-mallplaza-egana
2025-02-15 15:20:10,683 - INFO - Found 80 movie articles
2025-02-15 15:20:10,886 - INFO - Processing IMAX movie: CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-15 15:20:10,890 - INFO - Found 2 showtimes for CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-15 15:20:10,901 - INFO - Found 2 showtimes for CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-15 15:20:11,042 - INFO - WebDriver closed successfully
2025-02-15 15:20:11,043 - INFO - Successfully saved movies.json
2025-02-15 15:43:15,390 - INFO - Starting Chrome WebDriver...
2025-02-15 15:43:21,493 - INFO - patching driver executable /Users/claudio/Library/Application Support/undetected_chromedriver/undetected_chromedriver
2025-02-15 15:43:25,029 - ERROR - An error occurred: Message: unknown error: cannot connect to chrome at 127.0.0.1:54318
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 133.0.6943.55
Stacktrace:
0   undetected_chromedriver             0x00000001048b06b8 undetected_chromedriver + 4937400
1   undetected_chromedriver             0x00000001048a7b73 undetected_chromedriver + 4901747
2   undetected_chromedriver             0x0000000104465616 undetected_chromedriver + 435734
3   undetected_chromedriver             0x0000000104497d10 undetected_chromedriver + 642320
4   undetected_chromedriver             0x000000010448ef98 undetected_chromedriver + 606104
5   undetected_chromedriver             0x00000001044d6a08 undetected_chromedriver + 899592
6   undetected_chromedriver             0x00000001044d5ebf undetected_chromedriver + 896703
7   undetected_chromedriver             0x00000001044ccde3 undetected_chromedriver + 859619
8   undetected_chromedriver             0x000000010449ad7f undetected_chromedriver + 654719
9   undetected_chromedriver             0x000000010449c0de undetected_chromedriver + 659678
10  undetected_chromedriver             0x000000010486c2ad undetected_chromedriver + 4657837
11  undetected_chromedriver             0x0000000104871130 undetected_chromedriver + 4677936
12  undetected_chromedriver             0x0000000104877def undetected_chromedriver + 4705775
13  undetected_chromedriver             0x000000010487205a undetected_chromedriver + 4681818
14  undetected_chromedriver             0x000000010484492c undetected_chromedriver + 4495660
15  undetected_chromedriver             0x000000010488f838 undetected_chromedriver + 4802616
16  undetected_chromedriver             0x000000010488f9b7 undetected_chromedriver + 4802999
17  undetected_chromedriver             0x00000001048a099f undetected_chromedriver + 4872607
18  libsystem_pthread.dylib             0x00007ff80db2f253 _pthread_start + 99
19  libsystem_pthread.dylib             0x00007ff80db2abef thread_start + 15
Traceback (most recent call last):
  File "/Users/claudio/dev/imax-santiago/check-movies-json.py", line 36, in list_cinepolis_imax_movies
    driver = uc.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 443, in __init__
    super(Chrome, self).__init__(
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 674, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54318
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 133.0.6943.55
Stacktrace:
0   undetected_chromedriver             0x00000001048b06b8 undetected_chromedriver + 4937400
1   undetected_chromedriver             0x00000001048a7b73 undetected_chromedriver + 4901747
2   undetected_chromedriver             0x0000000104465616 undetected_chromedriver + 435734
3   undetected_chromedriver             0x0000000104497d10 undetected_chromedriver + 642320
4   undetected_chromedriver             0x000000010448ef98 undetected_chromedriver + 606104
5   undetected_chromedriver             0x00000001044d6a08 undetected_chromedriver + 899592
6   undetected_chromedriver             0x00000001044d5ebf undetected_chromedriver + 896703
7   undetected_chromedriver             0x00000001044ccde3 undetected_chromedriver + 859619
8   undetected_chromedriver             0x000000010449ad7f undetected_chromedriver + 654719
9   undetected_chromedriver             0x000000010449c0de undetected_chromedriver + 659678
10  undetected_chromedriver             0x000000010486c2ad undetected_chromedriver + 4657837
11  undetected_chromedriver             0x0000000104871130 undetected_chromedriver + 4677936
12  undetected_chromedriver             0x0000000104877def undetected_chromedriver + 4705775
13  undetected_chromedriver             0x000000010487205a undetected_chromedriver + 4681818
14  undetected_chromedriver             0x000000010484492c undetected_chromedriver + 4495660
15  undetected_chromedriver             0x000000010488f838 undetected_chromedriver + 4802616
16  undetected_chromedriver             0x000000010488f9b7 undetected_chromedriver + 4802999
17  undetected_chromedriver             0x00000001048a099f undetected_chromedriver + 4872607
18  libsystem_pthread.dylib             0x00007ff80db2f253 _pthread_start + 99
19  libsystem_pthread.dylib             0x00007ff80db2abef thread_start + 15

2025-02-15 15:43:25,034 - ERROR - Error closing WebDriver
Traceback (most recent call last):
  File "/Users/claudio/dev/imax-santiago/check-movies-json.py", line 113, in list_cinepolis_imax_movies
    driver.quit()
    ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
2025-02-15 15:43:25,034 - INFO - Successfully saved movies.json
2025-02-15 15:43:46,141 - INFO - Starting Chrome WebDriver...
2025-02-15 15:43:49,175 - INFO - patching driver executable /Users/claudio/Library/Application Support/undetected_chromedriver/undetected_chromedriver
2025-02-15 15:43:52,166 - ERROR - An error occurred: Message: unknown error: cannot connect to chrome at 127.0.0.1:54508
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 133.0.6943.55
Stacktrace:
0   undetected_chromedriver             0x000000010542c6b8 undetected_chromedriver + 4937400
1   undetected_chromedriver             0x0000000105423b73 undetected_chromedriver + 4901747
2   undetected_chromedriver             0x0000000104fe1616 undetected_chromedriver + 435734
3   undetected_chromedriver             0x0000000105013d10 undetected_chromedriver + 642320
4   undetected_chromedriver             0x000000010500af98 undetected_chromedriver + 606104
5   undetected_chromedriver             0x0000000105052a08 undetected_chromedriver + 899592
6   undetected_chromedriver             0x0000000105051ebf undetected_chromedriver + 896703
7   undetected_chromedriver             0x0000000105048de3 undetected_chromedriver + 859619
8   undetected_chromedriver             0x0000000105016d7f undetected_chromedriver + 654719
9   undetected_chromedriver             0x00000001050180de undetected_chromedriver + 659678
10  undetected_chromedriver             0x00000001053e82ad undetected_chromedriver + 4657837
11  undetected_chromedriver             0x00000001053ed130 undetected_chromedriver + 4677936
12  undetected_chromedriver             0x00000001053f3def undetected_chromedriver + 4705775
13  undetected_chromedriver             0x00000001053ee05a undetected_chromedriver + 4681818
14  undetected_chromedriver             0x00000001053c092c undetected_chromedriver + 4495660
15  undetected_chromedriver             0x000000010540b838 undetected_chromedriver + 4802616
16  undetected_chromedriver             0x000000010540b9b7 undetected_chromedriver + 4802999
17  undetected_chromedriver             0x000000010541c99f undetected_chromedriver + 4872607
18  libsystem_pthread.dylib             0x00007ff80db2f253 _pthread_start + 99
19  libsystem_pthread.dylib             0x00007ff80db2abef thread_start + 15
Traceback (most recent call last):
  File "/Users/claudio/dev/imax-santiago/check-movies-json.py", line 36, in list_cinepolis_imax_movies
    driver = uc.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 443, in __init__
    super(Chrome, self).__init__(
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 674, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54508
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 133.0.6943.55
Stacktrace:
0   undetected_chromedriver             0x000000010542c6b8 undetected_chromedriver + 4937400
1   undetected_chromedriver             0x0000000105423b73 undetected_chromedriver + 4901747
2   undetected_chromedriver             0x0000000104fe1616 undetected_chromedriver + 435734
3   undetected_chromedriver             0x0000000105013d10 undetected_chromedriver + 642320
4   undetected_chromedriver             0x000000010500af98 undetected_chromedriver + 606104
5   undetected_chromedriver             0x0000000105052a08 undetected_chromedriver + 899592
6   undetected_chromedriver             0x0000000105051ebf undetected_chromedriver + 896703
7   undetected_chromedriver             0x0000000105048de3 undetected_chromedriver + 859619
8   undetected_chromedriver             0x0000000105016d7f undetected_chromedriver + 654719
9   undetected_chromedriver             0x00000001050180de undetected_chromedriver + 659678
10  undetected_chromedriver             0x00000001053e82ad undetected_chromedriver + 4657837
11  undetected_chromedriver             0x00000001053ed130 undetected_chromedriver + 4677936
12  undetected_chromedriver             0x00000001053f3def undetected_chromedriver + 4705775
13  undetected_chromedriver             0x00000001053ee05a undetected_chromedriver + 4681818
14  undetected_chromedriver             0x00000001053c092c undetected_chromedriver + 4495660
15  undetected_chromedriver             0x000000010540b838 undetected_chromedriver + 4802616
16  undetected_chromedriver             0x000000010540b9b7 undetected_chromedriver + 4802999
17  undetected_chromedriver             0x000000010541c99f undetected_chromedriver + 4872607
18  libsystem_pthread.dylib             0x00007ff80db2f253 _pthread_start + 99
19  libsystem_pthread.dylib             0x00007ff80db2abef thread_start + 15

2025-02-15 15:43:52,171 - ERROR - Error closing WebDriver
Traceback (most recent call last):
  File "/Users/claudio/dev/imax-santiago/check-movies-json.py", line 113, in list_cinepolis_imax_movies
    driver.quit()
    ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
2025-02-15 15:43:52,172 - INFO - Successfully saved movies.json
2025-02-15 15:44:53,626 - INFO - Starting Chrome WebDriver...
2025-02-15 15:44:56,192 - INFO - patching driver executable /Users/claudio/Library/Application Support/undetected_chromedriver/undetected_chromedriver
2025-02-15 15:44:59,191 - ERROR - An error occurred: Message: unknown error: cannot connect to chrome at 127.0.0.1:54701
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 133.0.6943.55
Stacktrace:
0   undetected_chromedriver             0x00000001045706b8 undetected_chromedriver + 4937400
1   undetected_chromedriver             0x0000000104567b73 undetected_chromedriver + 4901747
2   undetected_chromedriver             0x0000000104125616 undetected_chromedriver + 435734
3   undetected_chromedriver             0x0000000104157d10 undetected_chromedriver + 642320
4   undetected_chromedriver             0x000000010414ef98 undetected_chromedriver + 606104
5   undetected_chromedriver             0x0000000104196a08 undetected_chromedriver + 899592
6   undetected_chromedriver             0x0000000104195ebf undetected_chromedriver + 896703
7   undetected_chromedriver             0x000000010418cde3 undetected_chromedriver + 859619
8   undetected_chromedriver             0x000000010415ad7f undetected_chromedriver + 654719
9   undetected_chromedriver             0x000000010415c0de undetected_chromedriver + 659678
10  undetected_chromedriver             0x000000010452c2ad undetected_chromedriver + 4657837
11  undetected_chromedriver             0x0000000104531130 undetected_chromedriver + 4677936
12  undetected_chromedriver             0x0000000104537def undetected_chromedriver + 4705775
13  undetected_chromedriver             0x000000010453205a undetected_chromedriver + 4681818
14  undetected_chromedriver             0x000000010450492c undetected_chromedriver + 4495660
15  undetected_chromedriver             0x000000010454f838 undetected_chromedriver + 4802616
16  undetected_chromedriver             0x000000010454f9b7 undetected_chromedriver + 4802999
17  undetected_chromedriver             0x000000010456099f undetected_chromedriver + 4872607
18  libsystem_pthread.dylib             0x00007ff80db2f253 _pthread_start + 99
19  libsystem_pthread.dylib             0x00007ff80db2abef thread_start + 15
Traceback (most recent call last):
  File "/Users/claudio/dev/imax-santiago/check-movies-json.py", line 36, in list_cinepolis_imax_movies
    driver = uc.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 443, in __init__
    super(Chrome, self).__init__(
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 674, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/claudio/dev/imax-santiago/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54701
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 133.0.6943.55
Stacktrace:
0   undetected_chromedriver             0x00000001045706b8 undetected_chromedriver + 4937400
1   undetected_chromedriver             0x0000000104567b73 undetected_chromedriver + 4901747
2   undetected_chromedriver             0x0000000104125616 undetected_chromedriver + 435734
3   undetected_chromedriver             0x0000000104157d10 undetected_chromedriver + 642320
4   undetected_chromedriver             0x000000010414ef98 undetected_chromedriver + 606104
5   undetected_chromedriver             0x0000000104196a08 undetected_chromedriver + 899592
6   undetected_chromedriver             0x0000000104195ebf undetected_chromedriver + 896703
7   undetected_chromedriver             0x000000010418cde3 undetected_chromedriver + 859619
8   undetected_chromedriver             0x000000010415ad7f undetected_chromedriver + 654719
9   undetected_chromedriver             0x000000010415c0de undetected_chromedriver + 659678
10  undetected_chromedriver             0x000000010452c2ad undetected_chromedriver + 4657837
11  undetected_chromedriver             0x0000000104531130 undetected_chromedriver + 4677936
12  undetected_chromedriver             0x0000000104537def undetected_chromedriver + 4705775
13  undetected_chromedriver             0x000000010453205a undetected_chromedriver + 4681818
14  undetected_chromedriver             0x000000010450492c undetected_chromedriver + 4495660
15  undetected_chromedriver             0x000000010454f838 undetected_chromedriver + 4802616
16  undetected_chromedriver             0x000000010454f9b7 undetected_chromedriver + 4802999
17  undetected_chromedriver             0x000000010456099f undetected_chromedriver + 4872607
18  libsystem_pthread.dylib             0x00007ff80db2f253 _pthread_start + 99
19  libsystem_pthread.dylib             0x00007ff80db2abef thread_start + 15

2025-02-15 15:44:59,195 - ERROR - Error closing WebDriver
Traceback (most recent call last):
  File "/Users/claudio/dev/imax-santiago/check-movies-json.py", line 113, in list_cinepolis_imax_movies
    driver.quit()
    ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
2025-02-15 15:44:59,196 - INFO - Successfully saved movies.json
2025-02-15 15:46:10,402 - INFO - Starting Chrome WebDriver...
2025-02-15 15:46:13,901 - INFO - patching driver executable /Users/claudio/Library/Application Support/undetected_chromedriver/undetected_chromedriver
2025-02-15 15:46:17,402 - INFO - Accessing URL: https://cinepolischile.cl/cartelera/santiago-oriente/cinepolis-mallplaza-egana
2025-02-15 15:46:38,456 - INFO - Found 80 movie articles
2025-02-15 15:46:38,699 - INFO - Processing IMAX movie: CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-15 15:46:38,703 - INFO - Found 2 showtimes for CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-15 15:46:38,715 - INFO - Found 1 showtimes for CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-15 15:46:38,970 - INFO - WebDriver closed successfully
2025-02-15 15:46:38,971 - INFO - Successfully saved movies.json
2025-02-16 13:15:11,789 - INFO - Starting Chrome WebDriver...
2025-02-16 13:15:12,377 - INFO - patching driver executable /home/claudio/.local/share/undetected_chromedriver/undetected_chromedriver
2025-02-16 13:15:14,092 - ERROR - An error occurred: Message: session not created: cannot connect to chrome at 127.0.0.1:59299
from session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 132.0.6834.110
Stacktrace:
#0 0x648ffd78cbba <unknown>
#1 0x648ffd22a790 <unknown>
#2 0x648ffd26a882 <unknown>
#3 0x648ffd269765 <unknown>
#4 0x648ffd25f093 <unknown>
#5 0x648ffd2b0369 <unknown>
#6 0x648ffd2af896 <unknown>
#7 0x648ffd2a1823 <unknown>
#8 0x648ffd26da88 <unknown>
#9 0x648ffd26ebf1 <unknown>
#10 0x648ffd75615b <unknown>
#11 0x648ffd75a0e2 <unknown>
#12 0x648ffd74301c <unknown>
#13 0x648ffd75acd4 <unknown>
#14 0x648ffd72748f <unknown>
#15 0x648ffd77b4f8 <unknown>
#16 0x648ffd77b6c9 <unknown>
#17 0x648ffd78ba36 <unknown>
#18 0x7e06d329caa4 <unknown>
#19 0x7e06d3329c3c <unknown>
Traceback (most recent call last):
  File "/home/claudio/dev/imax-movies/check-movies-json.py", line 36, in list_cinepolis_imax_movies
    driver = uc.Chrome(options=options)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:59299
from session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 132.0.6834.110
Stacktrace:
#0 0x648ffd78cbba <unknown>
#1 0x648ffd22a790 <unknown>
#2 0x648ffd26a882 <unknown>
#3 0x648ffd269765 <unknown>
#4 0x648ffd25f093 <unknown>
#5 0x648ffd2b0369 <unknown>
#6 0x648ffd2af896 <unknown>
#7 0x648ffd2a1823 <unknown>
#8 0x648ffd26da88 <unknown>
#9 0x648ffd26ebf1 <unknown>
#10 0x648ffd75615b <unknown>
#11 0x648ffd75a0e2 <unknown>
#12 0x648ffd74301c <unknown>
#13 0x648ffd75acd4 <unknown>
#14 0x648ffd72748f <unknown>
#15 0x648ffd77b4f8 <unknown>
#16 0x648ffd77b6c9 <unknown>
#17 0x648ffd78ba36 <unknown>
#18 0x7e06d329caa4 <unknown>
#19 0x7e06d3329c3c <unknown>

2025-02-16 13:15:14,094 - ERROR - Error closing WebDriver
Traceback (most recent call last):
  File "/home/claudio/dev/imax-movies/check-movies-json.py", line 113, in list_cinepolis_imax_movies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
2025-02-16 13:15:14,094 - INFO - Successfully saved movies.json
2025-02-16 13:15:31,280 - INFO - Starting Chrome WebDriver...
2025-02-16 13:15:31,674 - INFO - patching driver executable /home/claudio/.local/share/undetected_chromedriver/undetected_chromedriver
2025-02-16 13:15:36,500 - INFO - Accessing URL: https://cinepolischile.cl/cartelera/santiago-oriente/cinepolis-mallplaza-egana
2025-02-16 13:16:01,841 - INFO - Found 86 movie articles
2025-02-16 13:16:03,060 - INFO - Processing IMAX movie: CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-16 13:16:03,085 - INFO - Found 2 showtimes for CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-16 13:16:03,140 - INFO - Found 2 showtimes for CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-16 13:16:03,411 - INFO - WebDriver closed successfully
2025-02-16 13:16:03,414 - INFO - Successfully saved movies.json
2025-02-16 13:17:02,582 - INFO - Starting Chrome WebDriver...
2025-02-16 13:17:02,991 - INFO - patching driver executable /home/claudio/.local/share/undetected_chromedriver/undetected_chromedriver
2025-02-16 13:17:03,513 - ERROR - An error occurred: Message: session not created: cannot connect to chrome at 127.0.0.1:37801
from session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 132.0.6834.110
Stacktrace:
#0 0x5f9adf072bba <unknown>
#1 0x5f9adeb10790 <unknown>
#2 0x5f9adeb50882 <unknown>
#3 0x5f9adeb4f765 <unknown>
#4 0x5f9adeb45093 <unknown>
#5 0x5f9adeb96369 <unknown>
#6 0x5f9adeb95896 <unknown>
#7 0x5f9adeb87823 <unknown>
#8 0x5f9adeb53a88 <unknown>
#9 0x5f9adeb54bf1 <unknown>
#10 0x5f9adf03c15b <unknown>
#11 0x5f9adf0400e2 <unknown>
#12 0x5f9adf02901c <unknown>
#13 0x5f9adf040cd4 <unknown>
#14 0x5f9adf00d48f <unknown>
#15 0x5f9adf0614f8 <unknown>
#16 0x5f9adf0616c9 <unknown>
#17 0x5f9adf071a36 <unknown>
#18 0x7d0d70a9caa4 <unknown>
#19 0x7d0d70b29c3c <unknown>
Traceback (most recent call last):
  File "/home/claudio/dev/imax-movies/check-movies-json.py", line 36, in list_cinepolis_imax_movies
    driver = uc.Chrome(options=options)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:37801
from session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 132.0.6834.110
Stacktrace:
#0 0x5f9adf072bba <unknown>
#1 0x5f9adeb10790 <unknown>
#2 0x5f9adeb50882 <unknown>
#3 0x5f9adeb4f765 <unknown>
#4 0x5f9adeb45093 <unknown>
#5 0x5f9adeb96369 <unknown>
#6 0x5f9adeb95896 <unknown>
#7 0x5f9adeb87823 <unknown>
#8 0x5f9adeb53a88 <unknown>
#9 0x5f9adeb54bf1 <unknown>
#10 0x5f9adf03c15b <unknown>
#11 0x5f9adf0400e2 <unknown>
#12 0x5f9adf02901c <unknown>
#13 0x5f9adf040cd4 <unknown>
#14 0x5f9adf00d48f <unknown>
#15 0x5f9adf0614f8 <unknown>
#16 0x5f9adf0616c9 <unknown>
#17 0x5f9adf071a36 <unknown>
#18 0x7d0d70a9caa4 <unknown>
#19 0x7d0d70b29c3c <unknown>

2025-02-16 13:17:03,519 - ERROR - Error closing WebDriver
Traceback (most recent call last):
  File "/home/claudio/dev/imax-movies/check-movies-json.py", line 113, in list_cinepolis_imax_movies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
2025-02-16 13:17:03,519 - INFO - Successfully saved movies.json
2025-02-16 13:19:36,461 - INFO - Starting Chrome WebDriver...
2025-02-16 13:19:36,846 - INFO - patching driver executable /home/claudio/.local/share/undetected_chromedriver/undetected_chromedriver
2025-02-16 13:19:37,333 - ERROR - An error occurred: Message: session not created: cannot connect to chrome at 127.0.0.1:45297
from session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 132.0.6834.110
Stacktrace:
#0 0x5ab25f70dbba <unknown>
#1 0x5ab25f1ab790 <unknown>
#2 0x5ab25f1eb882 <unknown>
#3 0x5ab25f1ea765 <unknown>
#4 0x5ab25f1e0093 <unknown>
#5 0x5ab25f231369 <unknown>
#6 0x5ab25f230896 <unknown>
#7 0x5ab25f222823 <unknown>
#8 0x5ab25f1eea88 <unknown>
#9 0x5ab25f1efbf1 <unknown>
#10 0x5ab25f6d715b <unknown>
#11 0x5ab25f6db0e2 <unknown>
#12 0x5ab25f6c401c <unknown>
#13 0x5ab25f6dbcd4 <unknown>
#14 0x5ab25f6a848f <unknown>
#15 0x5ab25f6fc4f8 <unknown>
#16 0x5ab25f6fc6c9 <unknown>
#17 0x5ab25f70ca36 <unknown>
#18 0x78de0d69caa4 <unknown>
#19 0x78de0d729c3c <unknown>
Traceback (most recent call last):
  File "/home/claudio/dev/imax-movies/check-movies-json.py", line 36, in list_cinepolis_imax_movies
    driver = uc.Chrome(options=options)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:45297
from session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 132.0.6834.110
Stacktrace:
#0 0x5ab25f70dbba <unknown>
#1 0x5ab25f1ab790 <unknown>
#2 0x5ab25f1eb882 <unknown>
#3 0x5ab25f1ea765 <unknown>
#4 0x5ab25f1e0093 <unknown>
#5 0x5ab25f231369 <unknown>
#6 0x5ab25f230896 <unknown>
#7 0x5ab25f222823 <unknown>
#8 0x5ab25f1eea88 <unknown>
#9 0x5ab25f1efbf1 <unknown>
#10 0x5ab25f6d715b <unknown>
#11 0x5ab25f6db0e2 <unknown>
#12 0x5ab25f6c401c <unknown>
#13 0x5ab25f6dbcd4 <unknown>
#14 0x5ab25f6a848f <unknown>
#15 0x5ab25f6fc4f8 <unknown>
#16 0x5ab25f6fc6c9 <unknown>
#17 0x5ab25f70ca36 <unknown>
#18 0x78de0d69caa4 <unknown>
#19 0x78de0d729c3c <unknown>

2025-02-16 13:19:37,335 - ERROR - Error closing WebDriver
Traceback (most recent call last):
  File "/home/claudio/dev/imax-movies/check-movies-json.py", line 114, in list_cinepolis_imax_movies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
2025-02-16 13:19:37,335 - INFO - Successfully saved movies.json
2025-02-16 13:19:44,495 - INFO - Starting Chrome WebDriver...
2025-02-16 13:19:45,078 - INFO - patching driver executable /home/claudio/.local/share/undetected_chromedriver/undetected_chromedriver
2025-02-16 13:19:47,078 - INFO - Accessing URL: https://cinepolischile.cl/cartelera/santiago-oriente/cinepolis-mallplaza-egana
2025-02-16 13:20:12,496 - INFO - Found 86 movie articles
2025-02-16 13:20:13,858 - INFO - Processing IMAX movie: CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-16 13:20:13,883 - INFO - Found 2 showtimes for CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-16 13:20:13,950 - INFO - Found 2 showtimes for CAPITAN AMERICA: UN NUEVO MUNDO
2025-02-16 13:20:14,216 - INFO - WebDriver closed successfully
2025-02-16 13:20:14,217 - INFO - Successfully saved movies.json
2025-02-16 13:20:28,891 - INFO - Starting Chrome WebDriver...
2025-02-16 13:20:29,323 - INFO - patching driver executable /home/claudio/.local/share/undetected_chromedriver/undetected_chromedriver
2025-02-16 13:20:29,848 - ERROR - An error occurred: Message: session not created: cannot connect to chrome at 127.0.0.1:41999
from session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 132.0.6834.110
Stacktrace:
#0 0x64009bd42bba <unknown>
#1 0x64009b7e0790 <unknown>
#2 0x64009b820882 <unknown>
#3 0x64009b81f765 <unknown>
#4 0x64009b815093 <unknown>
#5 0x64009b866369 <unknown>
#6 0x64009b865896 <unknown>
#7 0x64009b857823 <unknown>
#8 0x64009b823a88 <unknown>
#9 0x64009b824bf1 <unknown>
#10 0x64009bd0c15b <unknown>
#11 0x64009bd100e2 <unknown>
#12 0x64009bcf901c <unknown>
#13 0x64009bd10cd4 <unknown>
#14 0x64009bcdd48f <unknown>
#15 0x64009bd314f8 <unknown>
#16 0x64009bd316c9 <unknown>
#17 0x64009bd41a36 <unknown>
#18 0x76dee429caa4 <unknown>
#19 0x76dee4329c3c <unknown>
Traceback (most recent call last):
  File "/home/claudio/dev/imax-movies/check-movies-json.py", line 36, in list_cinepolis_imax_movies
    driver = uc.Chrome(options=options)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/claudio/dev/imax-movies/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:41999
from session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 132.0.6834.110
Stacktrace:
#0 0x64009bd42bba <unknown>
#1 0x64009b7e0790 <unknown>
#2 0x64009b820882 <unknown>
#3 0x64009b81f765 <unknown>
#4 0x64009b815093 <unknown>
#5 0x64009b866369 <unknown>
#6 0x64009b865896 <unknown>
#7 0x64009b857823 <unknown>
#8 0x64009b823a88 <unknown>
#9 0x64009b824bf1 <unknown>
#10 0x64009bd0c15b <unknown>
#11 0x64009bd100e2 <unknown>
#12 0x64009bcf901c <unknown>
#13 0x64009bd10cd4 <unknown>
#14 0x64009bcdd48f <unknown>
#15 0x64009bd314f8 <unknown>
#16 0x64009bd316c9 <unknown>
#17 0x64009bd41a36 <unknown>
#18 0x76dee429caa4 <unknown>
#19 0x76dee4329c3c <unknown>

2025-02-16 13:20:29,849 - ERROR - Error closing WebDriver
Traceback (most recent call last):
  File "/home/claudio/dev/imax-movies/check-movies-json.py", line 114, in list_cinepolis_imax_movies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
2025-02-16 13:20:29,850 - INFO - Successfully saved movies.json
